name: Push GVMI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6.15']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: docker build . --file Dockerfile --tag our-image:latest
    - run: pip install gvmkit-build
    - run: docker build -t our-image:latest .
    - run: gvmkit-build our-image:latest
    - run: mkdir out
    - run: gvmkit-build our-image:latest --push > out/push
    - run: grep -i "hash link" out/push
    - name: "Deploy to Skynet using Resolver Link"
      uses: SkynetLabs/deploy-to-skynet-action@v2
      with:
          upload-dir: out
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
